export const SET_PARAMETERS = 'SET_PARAMETERS';

export const FETCH_ROWS_ERRORED = 'FETCH_ROWS_ERRORED';
export const FETCH_ROWS_LOADING = 'FETCH_ROWS_LOADING';
export const FETCH_ROWS_SUCCESS = 'FETCH_ROWS_SUCCESS';