package jdbcdemo.dao.repositories;

import java.sql.Connection;
import java.sql.SQLException;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.dao.uow.UnitOfWork;
import jdbcdemo.domain.Trener;

public class RepositoryTrener extends RepositoryBase<Trener> {
		
	public RepositoryTrener(Connection connection, ResultSetMapper<Trener> mapper, UnitOfWork uow) throws SQLException{
		super(connection, mapper, uow);
	}
	
	protected void setupInsert(Trener trener) throws SQLException {
		insert.setString(1, trener.getImie());
		insert.setString(2, trener.getNazwisko());
	}
	
	protected void setupUpdate(Trener trener) throws SQLException {
		update.setInt(1, trener.getId());
		update.setString(2, trener.getImie());
		update.setString(3, trener.getNazwisko());
	}


	@Override
	protected String tableName() {
		return "trener";
	}

	@Override
	protected String[] schema() {
		return new String[] {
			"id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
			"imie VARCHAR(30) NOT NULL",
			"nazwisko VARCHAR(30) NOT NULL"
		};
	}

	@Override
	protected String[] params() {
		return new String[] {
			"imie",
			"nazwisko"
		};
	}
}
