package jdbcdemo.dao.repositories;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.dao.uow.UnitOfWork;
import jdbcdemo.domain.Klub;

import java.sql.Connection;
import java.sql.SQLException;

public class RepositoryKlub extends RepositoryBase<Klub> {
    public RepositoryKlub(Connection connection, ResultSetMapper<Klub> mapper, UnitOfWork uow) throws SQLException {
        super(connection, mapper, uow);
    }

    @Override
    protected void setupInsert(Klub klub) throws SQLException {
        insert.setString(1, klub.getNazwa());
        insert.setInt(2, klub.getStadion());
        insert.setInt(3, klub.getTrener());

    }

    @Override
    protected void setupUpdate(Klub klub) throws SQLException {
        update.setInt(1, klub.getId());
        update.setString(2, klub.getNazwa());
        update.setInt(3, klub.getStadion());
        update.setInt(4, klub.getTrener());
    }

    @Override
    protected String tableName() {
        return "klub";
    }

    @Override
    protected String[] schema() {
        return new String[] {
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "nazwa VARCHAR(30) NOT NULL",
            "trener INT NOT NULL UNIQUE",
            "stadion INT NOT NULL UNIQUE",
            "CONSTRAINT fk_klub_trener FOREIGN KEY(trener) REFERENCES trener(id)",
            "CONSTRAINT fk_klub_stadion FOREIGN KEY(stadion) REFERENCES stadion(id)"
        };
    }

    @Override
    protected String[] params() {
        return new String[] {
            "nazwa",
            "trener",
            "stadion"
        };
    }
}
