package jdbcdemo.dao.repositories;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.dao.uow.UnitOfWork;
import jdbcdemo.domain.Stadion;

import java.sql.Connection;
import java.sql.SQLException;

public class RepositoryStadion extends RepositoryBase<Stadion> {

    public RepositoryStadion(Connection connection, ResultSetMapper<Stadion> mapper, UnitOfWork uow) throws SQLException {
        super(connection, mapper, uow);
    }

    protected void setupInsert(Stadion stadion) throws SQLException {
        insert.setString(1, stadion.getNazwa());
        insert.setString(2, stadion.getMiasto());
    }

    protected void setupUpdate(Stadion stadion) throws SQLException {
        update.setInt(1, stadion.getId());
        update.setString(2, stadion.getNazwa());
        update.setString(3, stadion.getMiasto());
    }

    @Override
    protected String tableName() {
        return "stadion";
    }

    @Override
    protected String[] schema() {
        return new String[] {
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "nazwa VARCHAR(30) NOT NULL",
            "miasto VARCHAR(30) NOT NULL"
        };
    }

    protected String[] params() {
        return new String[] {
            "nazwa",
            "miasto"
        };
    }
}
